import { useState } from 'react';
import { ChevronDown, Clock, ArrowRight, Zap, TrendingUp } from 'lucide-react';
import { type Recommendation } from '../api/client';
import { SectionIntro } from './Hint';

interface Props {
  recommendations: Recommendation[];
}

const PRIORITY = {
  high: {
    label: 'Do this week',
    bar: 'bg-red-500',
    badge: 'bg-red-100 text-red-700 border-red-200',
    border: 'border-l-red-400',
  },
  medium: {
    label: 'Do this month',
    bar: 'bg-yellow-500',
    badge: 'bg-yellow-100 text-yellow-700 border-yellow-200',
    border: 'border-l-yellow-400',
  },
  low: {
    label: 'Ongoing',
    bar: 'bg-green-500',
    badge: 'bg-green-100 text-green-700 border-green-200',
    border: 'border-l-green-400',
  },
} as const;

function RecommendationCard({ rec }: { rec: Recommendation }) {
  const [open, setOpen] = useState(false);
  const p = PRIORITY[rec.priority];

  return (
    <div
      className={`bg-white rounded-lg border border-gray-200 border-l-4 ${p.border} hover:shadow-sm transition-shadow cursor-pointer`}
      onClick={() => setOpen((v) => !v)}
    >
      <div className="flex items-start justify-between gap-3 p-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span
              className={`text-xs font-medium px-2 py-0.5 rounded-full border ${p.badge}`}
            >
              {p.label}
            </span>
            <p className="text-sm font-medium text-gray-800">{rec.title}</p>
          </div>
          <p className="text-xs text-gray-500 mt-1 leading-relaxed">
            {rec.description}
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0 mt-0.5">
          <span className="text-xs text-gray-400 flex items-center gap-1">
            <Clock className="w-3 h-3" />
            {rec.effort}
          </span>
          <ChevronDown
            className={`w-4 h-4 text-gray-400 transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
          />
        </div>
      </div>

      {open && (
        <div className="px-4 pb-4 flex flex-col gap-3 border-t border-gray-100 pt-3">
          <div className="flex flex-col gap-1.5">
            {rec.steps.map((step, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-gray-700">
                <ArrowRight className="w-3 h-3 mt-0.5 shrink-0 text-gray-400" />
                <span>{step}</span>
              </div>
            ))}
          </div>

          {rec.platforms && rec.platforms.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {rec.platforms.map((platform, i) => (
                <span
                  key={i}
                  className="text-xs bg-gray-50 rounded px-2 py-0.5 border border-gray-200 text-gray-600"
                >
                  {platform}
                </span>
              ))}
            </div>
          )}

          {rec.expectedImpact && (
            <p className="text-xs text-gray-500 flex items-start gap-1">
              <Zap className="w-3 h-3 mt-0.5 shrink-0 text-blue-500" />
              <span>{rec.expectedImpact}</span>
            </p>
          )}
        </div>
      )}
    </div>
  );
}

export function RecommendationsPanel({ recommendations }: Props) {
  if (!recommendations || recommendations.length === 0) return null;

  const groups = (
    ['high', 'medium', 'low'] as const
  )
    .map((p) => ({
      priority: p,
      items: recommendations.filter((r) => r.priority === p),
    }))
    .filter((g) => g.items.length > 0);

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6 flex flex-col gap-5">
      <div className="flex items-center gap-2">
        <TrendingUp className="w-5 h-5 text-blue-600" />
        <h3 className="text-base font-semibold text-gray-800">
          How to improve your AI visibility
        </h3>
      </div>
      <SectionIntro>
        Concrete to-do list generated by AI based on your actual scan results. Each item has steps, expected impact, and effort. <b>Red</b> = do this week. <b>Yellow</b> = this month. <b>Green</b> = ongoing. Click any card to expand the steps.
      </SectionIntro>

      {groups.map(({ priority, items }) => (
        <div key={priority} className="flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <div className={`w-2 h-2 rounded-full ${PRIORITY[priority].bar}`} />
            <span className="text-xs font-semibold text-gray-500 uppercase tracking-wide">
              {PRIORITY[priority].label} — {items.length} action
              {items.length > 1 ? 's' : ''}
            </span>
          </div>
          {items.map((rec, i) => (
            <RecommendationCard key={i} rec={rec} />
          ))}
        </div>
      ))}
    </div>
  );
}
